import {isPrincipalPolicy, isResourcePolicy, PolicyManager} from '@bleco/acl';
import {Class, ClassParams} from 'oso/dist/src/types';
import {Entity} from '@loopback/repository';
import {EntityClass} from '@bleco/query';
import {Relation} from 'oso/dist/src/filter';
import {buildClassFields} from './helper';
import {generate, generateActorScripts, generateResourceScripts} from './generation';

export interface EnforcerClassParams extends Omit<ClassParams, 'fields'> {}

interface ModelEntry<T extends Entity = Entity> {
  model: EntityClass<T>;
  fields: Record<string, Class | Relation>;
}

export class OsoPolicyBuilder {
  models: Map<string, ModelEntry>;

  constructor(protected readonly policyManager: PolicyManager) {}

  build() {
    this.models = new Map();

    const policies = this.policyManager.policies;
    for (const policy of policies) {
      addModelRecursively(policy.model, this.models);
    }
    return this;
  }

  async generatePolar() {
    return generate(writer => {
      writer.writeLine('# generated by oso-policy-builder');
      writer.writeLine('allow(principal, action, resource) if has_permission(principal, action, resource);');
      this.policyManager.policies.filter(isPrincipalPolicy).forEach(policy => generateActorScripts(writer, policy));
      this.policyManager.policies.filter(isResourcePolicy).forEach(policy => generateResourceScripts(writer, policy));
    });
  }
}

function addModelRecursively(model: EntityClass, models: Map<string, ModelEntry>) {
  const modelName = model.name;
  if (!models.has(modelName)) {
    const definition = model.definition;
    for (const name in definition.relations) {
      const relation = definition.relations[name];
      addModelRecursively(relation.target(), models);
    }

    models.set(modelName, {model, fields: buildClassFields(model)});
  }
}
